In [0]:
import numpy as np

In [0]:
docs = ["I enjoy playing TT", "I like playing TT"]

In [0]:
docs[0][0].split()

['I']

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=0, token_pattern=r"\b\w+\b")
vectorizer.fit(docs)

print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(docs)
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())

{'i': 1, 'enjoy': 0, 'playing': 3, 'tt': 4, 'like': 2}
(2, 5)
<class 'scipy.sparse.csr.csr_matrix'>
[[1 1 0 1 1]
 [0 1 1 1 1]]


In [0]:
print(vectorizer.vocabulary_)
print(vector.shape)
print(vector.toarray())

{'i': 1, 'enjoy': 0, 'playing': 3, 'tt': 4, 'like': 2}
(2, 5)
[[1 1 0 1 1]
 [0 1 1 1 1]]


In [0]:
x = []
y = []
for i in range(len(docs)):
  for j in range(len(docs[i].split())):
    t_x = []
    t_y = []
    for k in range(4):
      if(j==k):
        t_y.append(docs[i].split()[k])
        continue
      else:
        t_x.append(docs[i].split()[k])
    x.append(t_x)
    y.append(t_y)

In [0]:
x

[['enjoy', 'playing', 'TT'],
 ['I', 'playing', 'TT'],
 ['I', 'enjoy', 'TT'],
 ['I', 'enjoy', 'playing'],
 ['like', 'playing', 'TT'],
 ['I', 'playing', 'TT'],
 ['I', 'like', 'TT'],
 ['I', 'like', 'playing']]

In [0]:
y

[['I'], ['enjoy'], ['playing'], ['TT'], ['I'], ['like'], ['playing'], ['TT']]

In [0]:
x2 = []
y2 = []
for i in range(len(x)):
  x2.append(' '.join(x[i]))
  y2.append(' '.join(y[i]))

In [0]:
x2

['enjoy playing TT',
 'I playing TT',
 'I enjoy TT',
 'I enjoy playing',
 'like playing TT',
 'I playing TT',
 'I like TT',
 'I like playing']

In [0]:
y2

['I', 'enjoy', 'playing', 'TT', 'I', 'like', 'playing', 'TT']

In [0]:
vector_x = vectorizer.transform(x2)
vector_x.toarray()

array([[1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0]])

In [0]:
vector_y = vectorizer.transform(y2)
vector_y.toarray()

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM , Bidirectional,Dropout
from keras import backend as K
from keras.layers.advanced_activations import LeakyReLU
from keras import regularizers

Using TensorFlow backend.


In [0]:
model = Sequential()
model.add(Dense(3, activation='linear', input_shape=(5,)))
model.add(Dense(5,activation='sigmoid'))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 18        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 20        
Total params: 38
Trainable params: 38
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss='binary_crossentropy',optimizer='adam')

In [0]:
model.fit(vector_x, vector_y, epochs=1000, batch_size=4,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
8/8 [==============================] - 1s 107ms/step - loss: 0.9742
Epoch 2/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9688
Epoch 3/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9642
Epoch 4/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9593
Epoch 5/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9546
Epoch 6/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9501
Epoch 7/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9452
Epoch 8/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9404
Epoch 9/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9364
Epoch 10/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9315
Epoch 11/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9272
Epoch 12/1000
8/8 [==============================] - 0s 2ms/step - loss: 0.9230

In [0]:
model.predict(vector_x)

array([[0.14151314, 0.8418529 , 0.12190154, 0.00384882, 0.14743027],
       [0.13562405, 0.17135057, 0.14063832, 0.14222044, 0.14722058],
       [0.10961908, 0.01176494, 0.15443936, 0.8968668 , 0.05437657],
       [0.07129088, 0.05073237, 0.04657707, 0.00326315, 0.7923931 ],
       [0.13954145, 0.84038556, 0.1270298 , 0.00571874, 0.10531968],
       [0.13562405, 0.17135057, 0.14063832, 0.14222044, 0.14722058],
       [0.10803592, 0.01163793, 0.16068605, 0.9282912 , 0.03767052],
       [0.07021764, 0.05020627, 0.04871234, 0.00484982, 0.72208834]],
      dtype=float32)

In [0]:
[list(vectorizer.vocabulary_.keys())[0]]

['i']

In [0]:
vectorizer.transform([list(vectorizer.vocabulary_.keys())[1]]).toarray()

array([[1, 0, 0, 0, 0]])

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 18        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 20        
Total params: 38
Trainable params: 38
Non-trainable params: 0
_________________________________________________________________


In [0]:
from keras.models import Model
layer_name = 'dense_1'
intermediate_layer_model = Model(inputs=model.input,
                                 outputs=model.get_layer(layer_name).output)

In [0]:
for i in range(len(vectorizer.vocabulary_)):
  word = list(vectorizer.vocabulary_.keys())[i]
  word_vec = vectorizer.transform([list(vectorizer.vocabulary_.keys())[i]]).toarray()
  print(word, '\t', intermediate_layer_model.predict(word_vec))

i 	 [[ 0.19378224 -0.6309615   1.8917809 ]]
enjoy 	 [[-0.7392523 -1.0391831  0.5767987]]
playing 	 [[-0.8518311  -1.8652351  -0.83392346]]
tt 	 [[-1.313276    1.1554667   0.58792263]]
like 	 [[-0.9066584 -0.8294611  0.663727 ]]


# Measuring similarity between word vectors

In [0]:
a = word = list(vectorizer.vocabulary_.keys())[1]
word_vec_a = intermediate_layer_model.predict(vectorizer.transform([list(vectorizer.vocabulary_.keys())[1]]).toarray())

b = word = list(vectorizer.vocabulary_.keys())[4]
word_vec_b = intermediate_layer_model.predict(vectorizer.transform([list(vectorizer.vocabulary_.keys())[4]]).toarray())

In [0]:
word_vec_a

array([[-0.7392523, -1.0391831,  0.5767987]], dtype=float32)

In [0]:
np.sum(word_vec_a*word_vec_b)/((np.sqrt(np.sum(np.square(word_vec_a))))*np.sqrt(np.sum(np.square(word_vec_b))))

0.9796515

In [0]:
np.sum(np.square(word_vec_a - word_vec_b))

0.07956466