https://colab.research.google.com/drive/1ENG9UZjOFAB6KDp78oGMfUcFd_o6bHaJ

In [0]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.recurrent import SimpleRNN
from keras.layers.embeddings import Embedding
from keras.layers import LSTM
import numpy as np
from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
from keras.layers import RepeatVector

In [0]:
input_data = np.array([[1,2],[3,4]])
output_data = np.array([[3,4],[5,6]])

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1 = LSTM(1, activation = 'tanh', return_sequences=False,recurrent_initializer='Zeros',recurrent_activation='sigmoid')(inputs1)
#repvec = RepeatVector(2) (lstm1)
out= Dense(2, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
#model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model = Model(inputs=inputs1, outputs=out)
model.summary()




Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 1)                 12        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 4         
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(input_data.reshape(2,2,1), output_data,epochs=1000)

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[[1.1696435 2.8770094]]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2

In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
final_output = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]

In [0]:
final_output

array([1.1696435, 2.8770094], dtype=float32)

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1 = LSTM(1, activation = 'tanh', return_sequences=True,recurrent_initializer='Zeros',recurrent_activation='sigmoid')(inputs1)
#repvec = RepeatVector(2) (lstm1)
out= Dense(1, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
#model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model = Model(inputs=inputs1, outputs=out)
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 2, 1)              12        
_________________________________________________________________
dense_2 (Dense)              (None, 2, 1)              2         
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(input_data.reshape(2,2,1), output_data.reshape(2,2,1),epochs=1000)

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[[[2.194375]
  [3.097549]]]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
final_output_1 = hidden_layer_1 * model.get_weights()[3][0] + model.get_weights()[4]
final_output_1

array([2.194375], dtype=float32)

In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
final_output_2 = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]
final_output_2

array([3.097549], dtype=float32)

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1,state_h,state_c = LSTM(1, activation = 'tanh', return_sequences=True, return_state = True, recurrent_initializer='Zeros',recurrent_activation='sigmoid')(inputs1)
#repvec = RepeatVector(2) (lstm1)
#out= Dense(1, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
#model = Model(inputs=inputs1, outputs=out)
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
lstm_3 (LSTM)                [(None, 2, 1), (None, 1), 12        
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='mean_squared_error')
#model.fit(input_data.reshape(2,2,1), output_data.reshape(2,2,1),epochs=1)

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[array([[[0.00945035],
        [0.01547163]]], dtype=float32), array([[0.01547163]], dtype=float32), array([[0.09742781]], dtype=float32)]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
print(hidden_layer_1)

0.009450344087323944


In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
print(hidden_layer_2, input_t1_cell4)

0.015471625228386236 0.09742780553403282


In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM,Bidirectional
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1,state_fh,state_fc,state_bh,state_bc = Bidirectional(LSTM(1, activation = 'tanh', return_sequences=True, return_state = True, recurrent_initializer='Zeros',recurrent_activation='sigmoid'))(inputs1)
#repvec = RepeatVector(2) (lstm1)
#out= Dense(1, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
model = Model(inputs=inputs1, outputs=[lstm1, state_fh,state_fc,state_bh,state_bc])
#model = Model(inputs=inputs1, outputs=out)
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
bidirectional_1 (Bidirection [(None, 2, 2), (None, 1), 24        
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.weights

[<tf.Variable 'bidirectional_1/forward_lstm_4/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/forward_lstm_4/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/forward_lstm_4/bias:0' shape=(4,) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/backward_lstm_4/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/backward_lstm_4/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/backward_lstm_4/bias:0' shape=(4,) dtype=float32_ref>]

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[array([[[-0.20312288, -0.22649865],
        [-0.46045443, -0.11596721]]], dtype=float32), array([[-0.46045443]], dtype=float32), array([[-0.79382503]], dtype=float32), array([[-0.22649865]], dtype=float32), array([[-0.4975689]], dtype=float32)]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
print(hidden_layer_1)

-0.20312290517930642


In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
print(hidden_layer_2, input_t1_cell4)

-0.4604543785287757 -0.7938249906129276


In [0]:
input_t0 = 2
cell_state0 = 0
forget0 = input_t0*model.get_weights()[3][0][1] + model.get_weights()[5][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[3][0][0] + model.get_weights()[5][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[3][0][2] + model.get_weights()[5][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[3][0][3] + model.get_weights()[5][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
print(hidden_layer_1)

-0.11596720612373813


In [0]:
input_t1 = 1
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[4][0][1] + model.get_weights()[5][1] + input_t1*model.get_weights()[3][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[3][0][0] + model.get_weights()[5][0] + hidden_layer_1*model.get_weights()[4][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[3][0][2] + model.get_weights()[5][2]+ hidden_layer_1*model.get_weights()[4][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[3][0][3] + model.get_weights()[5][3]+ hidden_layer_1*model.get_weights()[4][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
print(hidden_layer_2, input_t1_cell4)

-0.2264986632061247 -0.4975689297326987


In [0]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.layers import LSTM
# prepare sequence
length = 2
seq = array([(i+1)/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000
# create LSTM
model = Sequential()
model.add(LSTM(5, activation = 'tanh',input_shape=(length, 1), return_sequences=True,recurrent_initializer='Zeros',recurrent_activation='sigmoid'))
model.add((Dense(1, activation='linear')))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, 2, 5)              140       
_________________________________________________________________
dense_3 (Dense)              (None, 2, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
# train LSTM
model.fit(X, y, epochs=10, batch_size=n_batch, verbose=2)

Epoch 1/10
 - 1s - loss: 0.6160
Epoch 2/10
 - 0s - loss: 0.6108
Epoch 3/10
 - 0s - loss: 0.6057
Epoch 4/10
 - 0s - loss: 0.6005
Epoch 5/10
 - 0s - loss: 0.5955
Epoch 6/10
 - 0s - loss: 0.5904
Epoch 7/10
 - 0s - loss: 0.5854
Epoch 8/10
 - 0s - loss: 0.5804
Epoch 9/10
 - 0s - loss: 0.5754
Epoch 10/10
 - 0s - loss: 0.5705


In [0]:
model.weights

[<tf.Variable 'lstm_5/kernel:0' shape=(1, 20) dtype=float32_ref>,
 <tf.Variable 'lstm_5/recurrent_kernel:0' shape=(5, 20) dtype=float32_ref>,
 <tf.Variable 'lstm_5/bias:0' shape=(20,) dtype=float32_ref>,
 <tf.Variable 'dense_3/kernel:0' shape=(5, 1) dtype=float32_ref>,
 <tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32_ref>]

In [0]:
X[0]

array([[0.5],
       [1. ]])

In [0]:
input_t0 = 0.5
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2

In [0]:
input_t1 = 1
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
final_output = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]

In [0]:
model.predict(X[0].reshape(1,2,1))

array([[[0.03199845],
        [0.04497762]]], dtype=float32)

In [0]:
final_output

array([-0.03194453], dtype=float32)

In [0]:
hidden_layer_1 * model.get_weights()[3][0] + model.get_weights()[4]

array([-0.00821053], dtype=float32)

In [0]:
y

array([[[0.5],
        [1. ]]])

In [0]:
# train LSTM
model.fit(X, y, epochs=10, batch_size=n_batch, verbose=2)
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:,0]:
	print('%.1f' % value)

Epoch 1/10
 - 0s - loss: 0.5655
Epoch 2/10
 - 0s - loss: 0.5607
Epoch 3/10
 - 0s - loss: 0.5558
Epoch 4/10
 - 0s - loss: 0.5510
Epoch 5/10
 - 0s - loss: 0.5462
Epoch 6/10
 - 0s - loss: 0.5414
Epoch 7/10
 - 0s - loss: 0.5367
Epoch 8/10
 - 0s - loss: 0.5319
Epoch 9/10
 - 0s - loss: 0.5272
Epoch 10/10
 - 0s - loss: 0.5225
0.1
0.1


In [0]:
result.shape

(1, 2, 1)

In [0]:
model.weights

[<tf.Variable 'lstm_5/kernel:0' shape=(1, 20) dtype=float32_ref>,
 <tf.Variable 'lstm_5/recurrent_kernel:0' shape=(5, 20) dtype=float32_ref>,
 <tf.Variable 'lstm_5/bias:0' shape=(20,) dtype=float32_ref>,
 <tf.Variable 'dense_3/kernel:0' shape=(5, 1) dtype=float32_ref>,
 <tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32_ref>]

In [0]:
model.get_weights()

[array([[-0.35308436, -0.40269458,  0.20396975,  0.06023806, -0.34106103,
          0.4242158 ,  0.55035204,  0.32777643, -0.43805128, -0.07643447,
          0.00675363,  0.41852856,  0.22229396,  0.0298297 , -0.17950772,
          0.0964174 , -0.08994686,  0.16300964,  0.42272446,  0.49065945]],
       dtype=float32),
 array([[-0.01016158,  0.00814309, -0.00854114,  0.00232737, -0.00773858,
         -0.00539176,  0.00733179, -0.00772044,  0.00010291, -0.00493106,
         -0.00851104,  0.00840269, -0.00849247,  0.00828977,  0.00855155,
         -0.01091932,  0.00814796, -0.00866112,  0.00243319, -0.00766833],
        [-0.01378287,  0.02022612, -0.01983138,  0.02049317, -0.01947042,
         -0.0073315 ,  0.02017239, -0.01961541,  0.01908619, -0.01874042,
         -0.02003439,  0.02011988, -0.02006152,  0.02019445,  0.0198801 ,
         -0.01208402,  0.02025229, -0.01979498,  0.02054662, -0.01941898],
        [-0.01361709,  0.01966412, -0.01919163,  0.02016347, -0.01875533,
         -0