In [0]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.recurrent import SimpleRNN
from keras.layers.embeddings import Embedding
from keras.layers import LSTM
import numpy as np
from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
from keras.layers import RepeatVector

In [0]:
input_data = np.array([[1,2],[3,4]])
output_data = np.array([[3,4],[5,6]])

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1 = LSTM(1, activation = 'tanh', return_sequences=False,recurrent_initializer='Zeros',recurrent_activation='sigmoid')(inputs1)
#repvec = RepeatVector(2) (lstm1)
out= Dense(2, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
#model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model = Model(inputs=inputs1, outputs=out)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 1)                 12        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 4         
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(input_data.reshape(2,2,1), output_data,epochs=1000)

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[[2.079641  1.8290598]]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2

In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
final_output = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]

In [0]:
final_output

array([2.079641 , 1.8290597], dtype=float32)

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1 = LSTM(1, activation = 'tanh', return_sequences=True,recurrent_initializer='Zeros',recurrent_activation='sigmoid')(inputs1)
#repvec = RepeatVector(2) (lstm1)
out= Dense(1, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
#model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
model = Model(inputs=inputs1, outputs=out)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 2, 1)              12        
_________________________________________________________________
dense_3 (Dense)              (None, 2, 1)              2         
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(input_data.reshape(2,2,1), output_data.reshape(2,2,1),epochs=1000)

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[[[1.7584195]
  [2.2500749]]]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
final_output_1 = hidden_layer_1 * model.get_weights()[3][0] + model.get_weights()[4]
final_output_1

array([1.7584196], dtype=float32)

In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
final_output_2 = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]
final_output_2

array([2.2500749], dtype=float32)

In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1,state_h,state_c = LSTM(1, activation = 'tanh', return_sequences=True, return_state = True, recurrent_initializer='Zeros',recurrent_activation='sigmoid')(inputs1)
#repvec = RepeatVector(2) (lstm1)
#out= Dense(1, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
#model = Model(inputs=inputs1, outputs=out)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         (None, 2, 1)              0         
_________________________________________________________________
lstm_6 (LSTM)                [(None, 2, 1), (None, 1), 12        
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='mean_squared_error')
#model.fit(input_data.reshape(2,2,1), output_data.reshape(2,2,1),epochs=1)

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[array([[[-0.256911 ],
        [-0.6683883]]], dtype=float32), array([[-0.6683883]], dtype=float32), array([[-0.96862674]], dtype=float32)]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
print(hidden_layer_1)

-0.256911018092609


In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
print(hidden_layer_2, input_t1_cell4)

-0.6683882766811402 -0.9686266609109275


In [0]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM,Bidirectional
from numpy import array
# define model
inputs1 = Input(shape=(2,1))
lstm1,state_fh,state_fc,state_bh,state_bc = Bidirectional(LSTM(1, activation = 'tanh', return_sequences=True, return_state = True, recurrent_initializer='Zeros',recurrent_activation='sigmoid'))(inputs1)
#repvec = RepeatVector(2) (lstm1)
#out= Dense(1, activation='linear')(lstm1)
#repvec = RepeatVector(2) (state_h)
model = Model(inputs=inputs1, outputs=[lstm1, state_fh,state_fc,state_bh,state_bc])
#model = Model(inputs=inputs1, outputs=out)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 2, 1)              0         
_________________________________________________________________
bidirectional_1 (Bidirection [(None, 2, 2), (None, 1), 24        
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.weights

[<tf.Variable 'bidirectional_1/forward_lstm_9/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/forward_lstm_9/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/forward_lstm_9/bias:0' shape=(4,) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/backward_lstm_9/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/backward_lstm_9/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'bidirectional_1/backward_lstm_9/bias:0' shape=(4,) dtype=float32_ref>]

In [0]:
print(model.predict(input_data[0].reshape(1,2,1)))

[array([[[-0.07460772, -0.05100038],
        [-0.06609192, -0.02083384]]], dtype=float32), array([[-0.06609192]], dtype=float32), array([[-0.23189402]], dtype=float32), array([[-0.05100038]], dtype=float32), array([[-0.19136184]], dtype=float32)]


In [0]:
input_t0 = 1
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
print(hidden_layer_1)

-0.0746077078148003


In [0]:
input_t1 = 2
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
print(hidden_layer_2, input_t1_cell4)

-0.06609191847032114 -0.23189399858181528


In [0]:
input_t0 = 2
cell_state0 = 0
forget0 = input_t0*model.get_weights()[3][0][1] + model.get_weights()[5][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[3][0][0] + model.get_weights()[5][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[3][0][2] + model.get_weights()[5][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[3][0][3] + model.get_weights()[5][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2
print(hidden_layer_1)

-0.020833835423206527


In [0]:
input_t1 = 1
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[4][0][1] + model.get_weights()[5][1] + input_t1*model.get_weights()[3][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[3][0][0] + model.get_weights()[5][0] + hidden_layer_1*model.get_weights()[4][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[3][0][2] + model.get_weights()[5][2]+ hidden_layer_1*model.get_weights()[4][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[3][0][3] + model.get_weights()[5][3]+ hidden_layer_1*model.get_weights()[4][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
print(hidden_layer_2, input_t1_cell4)

-0.05100036776625001 -0.191361832062391


In [0]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import TimeDistributed
from keras.layers import LSTM
# prepare sequence
length = 2
seq = array([(i+1)/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000
# create LSTM
model = Sequential()
model.add(LSTM(5, activation = 'tanh',input_shape=(length, 1), return_sequences=True,recurrent_initializer='Zeros',recurrent_activation='sigmoid'))
model.add((Dense(1, activation='linear')))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_23 (LSTM)               (None, 2, 5)              140       
_________________________________________________________________
dense_15 (Dense)             (None, 2, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
# train LSTM
model.fit(X, y, epochs=10, batch_size=n_batch, verbose=2)

Epoch 1/10
 - 2s - loss: 0.6035
Epoch 2/10
 - 0s - loss: 0.6011
Epoch 3/10
 - 0s - loss: 0.5987
Epoch 4/10
 - 0s - loss: 0.5962
Epoch 5/10
 - 0s - loss: 0.5938
Epoch 6/10
 - 0s - loss: 0.5914
Epoch 7/10
 - 0s - loss: 0.5890
Epoch 8/10
 - 0s - loss: 0.5866
Epoch 9/10
 - 0s - loss: 0.5842
Epoch 10/10
 - 0s - loss: 0.5818


In [0]:
model.weights

[<tf.Variable 'lstm_22/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'lstm_22/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'lstm_22/bias:0' shape=(4,) dtype=float32_ref>,
 <tf.Variable 'dense_14/kernel:0' shape=(1, 1) dtype=float32_ref>,
 <tf.Variable 'dense_14/bias:0' shape=(1,) dtype=float32_ref>]

In [0]:
X[0]

array([[0.5],
       [1. ]])

In [0]:
input_t0 = 0.5
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))
cell_state1 = forget1 * cell_state0
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)
input_t0_cell3 = input_t0_cell2*input_t0_2
input_t0_cell4 = input_t0_cell3 + cell_state1
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2

In [0]:
input_t1 = 1
cell_state1 = input_t0_cell4
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))
cell_state2 = cell_state1 * forget_22
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)
input_t1_cell3 = input_t1_cell2*input_t1_2
input_t1_cell4 = input_t1_cell3 + cell_state2
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2
final_output = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]

In [0]:
model.predict(X[0].reshape(1,2,1))

array([[[0.02046466],
        [0.03626223]]], dtype=float32)

In [0]:
final_output

array([0.03626223], dtype=float32)

In [0]:
hidden_layer_1 * model.get_weights()[3][0] + model.get_weights()[4]

array([0.02046467], dtype=float32)

In [0]:
y

array([[[0. ],
        [0.5]]])

In [0]:
result.shape

(1, 5, 1)

In [0]:
# train LSTM
model.fit(X, y, epochs=10, batch_size=n_batch, verbose=2)
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:,0]:
	print('%.1f' % value)

Epoch 1/10
 - 1s - loss: 0.2982
Epoch 2/10
 - 0s - loss: 0.2943
Epoch 3/10
 - 0s - loss: 0.2905
Epoch 4/10
 - 0s - loss: 0.2866
Epoch 5/10
 - 0s - loss: 0.2828
Epoch 6/10
 - 0s - loss: 0.2791
Epoch 7/10
 - 0s - loss: 0.2753
Epoch 8/10
 - 0s - loss: 0.2716
Epoch 9/10
 - 0s - loss: 0.2679
Epoch 10/10
 - 0s - loss: 0.2642
0.0
0.0
-0.0
-0.0
-0.0


In [0]:
model.weights

[<tf.Variable 'lstm_11/kernel:0' shape=(1, 20) dtype=float32_ref>,
 <tf.Variable 'lstm_11/recurrent_kernel:0' shape=(5, 20) dtype=float32_ref>,
 <tf.Variable 'lstm_11/bias:0' shape=(20,) dtype=float32_ref>,
 <tf.Variable 'dense_3/kernel:0' shape=(5, 1) dtype=float32_ref>,
 <tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32_ref>]

In [0]:
model.get_weights()

[array([[-0.4062789 , -0.19615704,  0.3040961 ,  0.04107479,  0.418955  ,
          0.20863643,  0.2202466 , -0.45922732,  0.42719266,  0.10439701,
         -0.37499163, -0.10766914, -0.4079143 ,  0.26807642, -0.14095676,
         -0.15014175, -0.21194729,  0.31018722,  0.02566439,  0.2411718 ]],
       dtype=float32),
 array([[-3.3847085e-01, -4.1197088e-01,  3.9774144e-01, -3.2600041e-02,
         -2.9357016e-01,  2.4165198e-01, -1.9913433e-01, -1.5972325e-01,
         -4.7611341e-02, -2.1787867e-01, -1.6926934e-01,  8.1794180e-02,
         -1.7449659e-01, -2.4008021e-01, -2.4328016e-02, -3.1740549e-01,
          1.7650011e-01,  1.7581573e-01,  7.7375181e-02,  1.6153188e-02],
        [ 8.5580356e-02, -2.7733675e-01, -1.0733363e-01, -7.7101134e-02,
         -3.3647496e-02,  2.1752062e-01,  5.8931813e-02,  1.5544024e-01,
          5.3394157e-02, -1.4351451e-01,  3.0157241e-01,  6.4627632e-02,
         -6.5746047e-02, -2.7889735e-01,  5.2349913e-01,  1.9322208e-01,
          8.0057524e-