In [0]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.recurrent import SimpleRNN
from keras.layers.embeddings import Embedding
from keras.layers import LSTM
import numpy as np
from keras.utils import to_categorical

Using TensorFlow backend.


In [0]:
#define documents
docs = ['this is','is an']
# define class labels
labels = ['an','example']


from collections import Counter
counts = Counter()
for i,review in enumerate(docs+labels):
  counts.update(review.split())
words = sorted(counts, key=counts.get, reverse=True)
vocab_size=len(words)
word_to_int = {word: i for i, word in enumerate(words, 1)}

encoded_docs = []
for doc in docs:
  encoded_docs.append([word_to_int[word] for word in doc.split()])
encoded_labels = []
for label in labels:
  encoded_labels.append([word_to_int[word] for word in label.split()])

In [0]:
# pad documents to a max length of 2 words
max_length = 2
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='pre')
print(padded_docs)

[[3 1]
 [1 2]]


In [0]:
# processing the output dataset
one_hot_encoded_labels = to_categorical(encoded_labels, num_classes=5)
print(one_hot_encoded_labels)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [0]:
one_hot_encoded_labels = [1,0]

In [0]:
# define the model
embed_length=1
max_length=2
model = Sequential()
model.add(LSTM(1,activation='tanh', return_sequences=False,recurrent_initializer='Zeros',recurrent_activation='sigmoid',
               input_shape=(max_length,embed_length),unroll=True))
model.add(Dense(5, activation='softmax'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_19 (LSTM)               (None, 1)                 12        
_________________________________________________________________
dense_18 (Dense)             (None, 5)                 10        
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.fit(padded_docs.reshape(2,2,1),np.array(one_hot_encoded_labels),epochs=500)

Epoch 1/500
2/2 [==============================] - 2s 752ms/step - loss: 0.4990 - acc: 0.8000
Epoch 2/500
2/2 [==============================] - 0s 4ms/step - loss: 0.4987 - acc: 0.8000
Epoch 3/500
2/2 [==============================] - 0s 3ms/step - loss: 0.4984 - acc: 0.8000
Epoch 4/500
2/2 [==============================] - 0s 3ms/step - loss: 0.4980 - acc: 0.8000
Epoch 5/500
2/2 [==============================] - 0s 1ms/step - loss: 0.4977 - acc: 0.8000
Epoch 6/500
2/2 [==============================] - 0s 1ms/step - loss: 0.4974 - acc: 0.8000
Epoch 7/500
2/2 [==============================] - 0s 3ms/step - loss: 0.4971 - acc: 0.8000
Epoch 8/500
2/2 [==============================] - 0s 1ms/step - loss: 0.4967 - acc: 0.8000
Epoch 9/500
2/2 [==============================] - 0s 1ms/step - loss: 0.4964 - acc: 0.8000
Epoch 10/500
2/2 [==============================] - 0s 2ms/step - loss: 0.4961 - acc: 0.8000
Epoch 11/500
2/2 [==============================] - 0s 2ms/step - loss: 0.495

In [0]:
model.weights

[<tf.Variable 'lstm_19/kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'lstm_19/recurrent_kernel:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'lstm_19/bias:0' shape=(4,) dtype=float32_ref>,
 <tf.Variable 'dense_18/kernel:0' shape=(1, 5) dtype=float32_ref>,
 <tf.Variable 'dense_18/bias:0' shape=(5,) dtype=float32_ref>]

In [0]:
model.get_weights()

[array([[-0.14517151,  0.6083162 , -1.1783044 ,  0.13638282]],
       dtype=float32),
 array([[-0.84423834, -0.79510975,  0.7330096 , -0.88780767]],
       dtype=float32),
 array([ 0.69750947,  1.6316813 , -0.5267366 ,  0.72982365], dtype=float32),
 array([[ 1.3478366 ,  0.19629796, -0.42218098,  1.4451593 , -0.4760761 ]],
       dtype=float32),
 array([-0.3792744 , -0.4455305 ,  0.4068997 , -0.37427032,  0.40237203],
       dtype=float32)]

In [0]:
padded_docs[0]

array([3, 1], dtype=int32)

In [0]:
model.predict(padded_docs[0].reshape(1,2,1))

array([[0.05610514, 0.11013522, 0.38451442, 0.0529648 , 0.39628044]],
      dtype=float32)

In [0]:
model.get_weights()[0]

array([[-0.14517151,  0.6083162 , -1.1783044 ,  0.13638282]],
      dtype=float32)

In [0]:
input_t0 = 3
cell_state0 = 0
forget0 = input_t0*model.get_weights()[0][0][1] + model.get_weights()[2][1]
forget1 = 1/(1+np.exp(-(forget0)))

In [0]:
cell_state1 = forget1 * cell_state0

In [0]:
input_t0_1 = input_t0*model.get_weights()[0][0][0] + model.get_weights()[2][0]
input_t0_2 = 1/(1+np.exp(-(input_t0_1)))

In [0]:
input_t0_cell1 = input_t0*model.get_weights()[0][0][2] + model.get_weights()[2][2]
input_t0_cell2 = np.tanh(input_t0_cell1)

In [0]:
input_t0_cell3 = input_t0_cell2*input_t0_2

In [0]:
input_t0_cell4 = input_t0_cell3 + cell_state1

In [0]:
output_t0_1 = input_t0*model.get_weights()[0][0][3] + model.get_weights()[2][3]
output_t0_2 = 1/(1+np.exp(-output_t0_1))

In [0]:
hidden_layer_1 = np.tanh(input_t0_cell4)*output_t0_2

In [0]:
input_t1 = 1
cell_state1 = input_t0_cell4

In [0]:
forget21 = hidden_layer_1*model.get_weights()[1][0][1] + model.get_weights()[2][1] + input_t1*model.get_weights()[0][0][1]
forget_22 = 1/(1+np.exp(-(forget21)))

In [0]:
cell_state2 = cell_state1 * forget_22

In [0]:
input_t1_1 = input_t1*model.get_weights()[0][0][0] + model.get_weights()[2][0] + hidden_layer_1*model.get_weights()[1][0][0]
input_t1_2 = 1/(1+np.exp(-(input_t1_1)))

In [0]:
input_t1_cell1 = input_t1*model.get_weights()[0][0][2] + model.get_weights()[2][2]+ hidden_layer_1*model.get_weights()[1][0][2]
input_t1_cell2 = np.tanh(input_t1_cell1)

In [0]:
input_t1_cell3 = input_t1_cell2*input_t1_2

In [0]:
input_t1_cell4 = input_t1_cell3 + cell_state2

In [0]:
output_t1_1 = input_t1*model.get_weights()[0][0][3] + model.get_weights()[2][3]+ hidden_layer_1*model.get_weights()[1][0][3]
output_t1_2 = 1/(1+np.exp(-output_t1_1))

In [0]:
hidden_layer_2 = np.tanh(input_t1_cell4)*output_t1_2

In [0]:
final_output = hidden_layer_2 * model.get_weights()[3][0] + model.get_weights()[4]

In [0]:
np.exp(final_output)/np.sum(np.exp(final_output))

array([0.05610514, 0.11013523, 0.3845144 , 0.05296481, 0.39628044],
      dtype=float32)